$c = [IO.File]::ReadAllText('D:/apps/Trae CN/resources/app/node_modules/@byted-icube/ai-modules-chat/dist/index.js')
Write-Host "File size: $($c.Length)"
Write-Host "_self=this pos: $($c.IndexOf('var _self=this'))"
Write-Host "_self.resumeChat pos: $($c.IndexOf('_self.resumeChat'))"
Write-Host "uj.getInstance().resolve(BR) pos: $($c.IndexOf('uj.getInstance().resolve(BR)'))"
Write-Host "e.resumeCount++ pos: $($c.IndexOf('e.resumeCount++'))"
Write-Host "resumeCount<3 pos: $($c.IndexOf('resumeCount<3'))"
Write-Host "MC-no-method pos: $($c.IndexOf('MC-no-method'))"
Write-Host "[v10-bg] pos: $($c.IndexOf('[v10-bg]'))"
Write-Host "[v19-bg] pos: $($c.IndexOf('[v19-bg]'))"
