$c = [IO.File]::ReadAllText('D:/apps/Trae CN/resources/app/node_modules/@byted-icube/ai-modules-chat/dist/index.js')
Write-Host "File size: $($c.Length)"
Write-Host "_ts=function pos: $($c.IndexOf('_ts=function'))"
Write-Host "[v19-bg] pos: $($c.IndexOf('[v19-bg]'))"
$docCheck = "typeof document!=="
Write-Host "typeof document check pos: $($c.IndexOf($docCheck))"
Write-Host "VC-skip pos: $($c.IndexOf('VC-skip'))"
Write-Host "dispatchEvent focus pos: $($c.IndexOf("dispatchEvent(new Event('focus'))"))"
Write-Host "MC-validate-ignore pos: $($c.IndexOf('MC-validate-ignore'))"
Write-Host "resolve(Di) pos: $($c.IndexOf('resolve(Di)'))"
